name: Deploy to Vercel
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  info:
    name: Gather info for jobs
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.target_branch.outputs.branch }}
      env_name: ${{ steps.environment.outputs.name }}
    steps:
      - name: Get target branch
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=${branch}" >> $GITHUB_OUTPUT

          echo "::group::Branch"
          echo 'branch: '${branch}
          echo "::endgroup::"
        id: target_branch

      - name: Get environment
        run: |
          env=dev
          if [ "${{ steps.target_branch.outputs.name }}" = "main" ]
          then
            env=prod
          fi
          echo "name=${env}" >> $GITHUB_OUTPUT

          echo "::group::Environment"
          echo 'environment: '${env}
          echo "::endgroup::"
        id: environment

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [info]
    environment:
      name: ${{ needs.info.outputs.env_name }}
    steps:
      - name: install ssh keys
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Pull latest from Github
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_WORK_DIR }} && git checkout ${{ needs.info.outputs.branch }} && git pull && exit"

      - name: Create .env
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "cd ${{ secrets.SSH_WORK_DIR }} && \
          CLOUD_FOLDER_NAME=${{ secrets.CLOUD_FOLDER_NAME }} \
          CLOUD_NAME=${{ secrets.CLOUD_NAME }} \
          CLOUDINARY_API_KEY=${{ secrets.API_KEY }} \
          CLOUDINARY_API_SECRET=${{ secrets.API_SECRET }} \
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_PASS=${{ secrets.DB_PASS }} \
          DB_USER=${{ secrets.DB_USER }} \
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
          NODE_VERSION=${{ vars.NODE_VERSION }} \
          SERVER_NAME=${{ vars.SERVER_NAME }} \
          SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} \
          SENDGRID_EMAIL_SENDER=${{ secrets.SENDGRID_EMAIL_SENDER }} \
          bash ./create_env && \
          exit"

      - name: Build the app
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_WORK_DIR }} && yarn && yarn prisma:generate && yarn build && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
