name: Run All Tests
on:
  pull_request:
    branches: [develop, staging]
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION || "latest" }}

      - name: Install dependencies
        run: yarn

      - name: Lint project
        run: npm run lint

      # TODO: fix playwright tests and add back into gh actions
      # - name: Install Playwright
      #   run: npx playwright install --with-deps

      - name: Run Jest
        run: npm run test:unit
      # - name: Run Playwright tests
      #   run: npm run test:e2e
